### ISSUE TITLE
Raspberry Pi 4 does not connect to Victron devices

### ISSUE THREAD

**Issue by jonashoechst** [tRackIT-Systems/pysmartsolar#2]
Looking at the log messages, a *Page Timeout* can be found, however the is no indication of what the problem could be:

```
DEBUG:root:Logging level: DEBUG
INFO:smartsolar:Starting manager
INFO:smartsolar:Connecting to nearest VEDevice
INFO:smartsolar:[cd:05:1c:cc:c2:e8] Discovered VictronEnergy device "CD-05-1C-CC-C2-E8", RSSI: -51
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  Address: CD:05:1C:CC:C2:E8
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  AddressType: random
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  Alias: CD-05-1C-CC-C2-E8
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  Paired: 0
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  Trusted: 1
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  Blocked: 0
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  LegacyPairing: 0
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  RSSI: -51
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  Connected: 0
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  UUIDs: dbus.Array([], signature=dbus.Signature('s'), variant_level=1)
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  Adapter: /org/bluez/hci0
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  ManufacturerData: dbus.Dictionary({dbus.UInt16(737): dbus.Array([dbus.Byte(16), dbus.Byte(2), dbus.Byte(83), dbus.Byte(160), dbus.Byte(1), dbus.Byte(170), dbus.Byte(48), dbus.Byte(206), dbus.Byte(195), dbus.Byte(172), dbus.Byte(148), dbus.Byte(146), dbus.Byte(106), dbus.Byte(97), dbus.Byte(173), dbus.Byte(224), dbus.Byte(138), dbus.Byte(160), dbus.Byte(179), dbus.Byte(26)], signature=dbus.Signature('y'), variant_level=1)}, signature=dbus.Signature('qv'), variant_level=1)
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8]  ServicesResolved: 0
INFO:smartsolar:[cd:05:1c:cc:c2:e8] Selected nearest device "CD-05-1C-CC-C2-E8"
INFO:smartsolar:Creating VictronEnergy pairing agent
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8] Attempting to pair...
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8] Response: org.bluez.Error.ConnectionAttemptFailed: Page Timeout
DEBUG:smartsolar:[cd:05:1c:cc:c2:e8] Paired: 0
ERROR:smartsolar:[cd:05:1c:cc:c2:e8] Pairing failed, rasing RuntimeError.
INFO:smartsolar:Querying finished.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/pysmartsolar/smartsolar/__main__.py", line 25, in <module>
    values = read_nearest_vedevice(**args.__dict__)
  File "/home/pi/pysmartsolar/smartsolar/__init__.py", line 434, in read_nearest_vedevice
    d = manager.connect_nearest_vedevice(discovery_duration, passkey=passkey)
  File "/home/pi/pysmartsolar/smartsolar/__init__.py", line 417, in connect_nearest_vedevice
    raise RuntimeError("Pairing VictronEnergy Device '%s' [%s] failed.", d.alias(), d.mac_address)
RuntimeError: ("Pairing VictronEnergy Device '%s' [%s] failed.", dbus.String('CD-05-1C-CC-C2-E8', variant_level=1), 'cd:05:1c:cc:c2:e8')
```

**Comment by jonashoechst** [comment]
Manually pairing with the device with bluetoothctl also showed no effect, as in paring was not possible.

**Comment by jonashoechst** [comment]
Various old fixing approaches:
https://forum-raspberrypi.de/forum/thread/51345-loesung-fuer-bluetooth-probleme-mit-pi400/
https://github.com/RPi-Distro/pi-bluetooth/pull/21
https://forums.raspberrypi.com/viewtopic.php?t=304000&sid=4974412c41593c887754ce9ea7093e4b&start=50
https://peppe8o.com/fixed-connect-bluetooth-headphones-with-your-raspberry-pi/
https://raspberrypi.stackexchange.com/questions/122429/raspberry-pi-4-wont-pair-to-bluetooth-devices
